select * from actor limit 10;

-- Display each store with current film available count

select s.store_id,f.title,count(*) as stock
from store as s
join inventory as i
using (store_id)
join film as f
using (film_id)
group by s.store_id,f.title
order by s.store_id,f.title,stock;

-- Top 10 Highest Paying Customer

with max_pay as (select customer_id,
                        sum(amount) as "total_pay",
                        dense_rank() over(order by sum(amount)desc ) as rank
                 from payment
                 group by customer_id)

select customer.first_name || ' ' || customer.last_name , max_pay.total_pay
from customer
join max_pay
using(customer_id)
where max_pay.rank<=10
order by rank;


-- Movie category which generate most revenue

--payment , rental , inventory, film , film_category

with category_revenue as (select fc.category_id, rank() over (order by sum(p.amount) desc) as rank, sum(p.amount) as "total_revenu"
                           from payment as p
                                   join rental as r using (rental_id)
                                   join inventory as i using (inventory_id)

                                   join film_category as fc using (film_id)
                                   join category as c using (category_id)
                          group by fc.category_id)

select category.name , category_revenue.total_revenu
from category
         join category_revenue
              using(category_id)
where rank=1;

-- SELECT
--     c.name,
--     SUM(p.amount) AS total_revenue
-- FROM payment p
--          JOIN rental r USING (rental_id)
--          JOIN inventory i USING (inventory_id)
--          JOIN film_category fc USING (film_id)
--          JOIN category c USING (category_id)
-- GROUP BY c.category_id, c.name
-- ORDER BY total_revenue DESC
--     FETCH FIRST 1 ROWS WITH TIES;


-- Actors who did more than 4 movies together

select actor1.first_name || ' ' || actor1.last_name,
       actor2.first_name || ' ' || actor2.last_name,
       count(fa1.film_id) as movie
from actor as actor1
join film_actor as fa1
on actor1.actor_id = fa1.actor_id
join film_actor as fa2
on fa1.film_id = fa2.film_id and actor1.actor_id < fa2.actor_id
join actor as actor2
on fa2.actor_id = actor2.actor_id
group by actor1.first_name, actor1.last_name, actor2.first_name, actor2.last_name
having count(fa1.film_id)>=5
order by movie desc;

-- Revenue per store

select s.store_id,
       sum(p.amount) as revenue
from store s
join staff st
using(store_id)
join payment p
using (staff_id)
group by s.store_id;

-- Movie with more than 3 actor

select f.title,
       count(fa.actor_id) as actor
from film f
join film_actor fa
using (film_id)
group by f.title
having count(fa.actor_id)>3
order by actor desc;

-- Categorize movie based on duration

select
    film.title,
    case
       when length<60 then 'Short'
       when length>60 and length<120 then 'medium'
       else 'long'
       end
from film;

-- Highest rental cities per country

with city_rentals as (
    select
        co.country,
        ci.city,
        count(r.rental_id) as rentals,
        dense_rank() over(partition by co.country_id order by count(r.rental_id) desc) as rank
    from country co
    join city ci using (country_id)
    join address a using (city_id)
    join customer c using (address_id)
    join rental r using (customer_id)
    group by co.country, ci.city, co.country_id


)

select country , city , rentals
from city_rentals
where rank=1
order by country;

-- Movie with the highest revenue

select
    f.title as movie_title,
    count(p.payment_id) as total_rentals,
    sum(p.amount) as total_revenue
from film f
         join inventory i on f.film_id = i.film_id
         join rental r on i.inventory_id = r.inventory_id
         join payment p on r.rental_id = p.rental_id
group by f.film_id, f.title
order by total_revenue desc
limit 1;


-- film with language

select
    f.title as movie_title,
    l.name as movie_language
from film f
         join language l on f.language_id = l.language_id
order by f.title;

-- 1. Retrieve each film titles with their category, release_year and rating.
select film.title,
       category.name as category,
       film.release_year,
       film.rating
from film
join film_category
using(film_id)
join category
using (category_id);

-- 2. Categories and the count of the movies those related to that category.
select
       category.name as category,
       count(film_id)
from film_category
join category
    using (category_id)
group by category.name;

-- 3. Calculate the total rental revenue generated by each film category.
select c.name as category,
       sum(amount) as total_revenue
from payment p
join rental r
using(rental_id)
join inventory i
using(inventory_id)
join film_category fc
using (film_id)
join category c
using (category_id)
group by c.name
order by total_revenue desc;


-- 4. Find the customers whose total spending is greater than average spending of customers who made at least one payment.
with avg_spending as (
    select avg("Total Spent") as "Avg Spent"
    from(
        select
               sum(payment.amount) as "Total Spent"
        from payment
        group by customer_id
    ) as "total_spent"
)

select customer.first_name || ' ' || customer.last_name as "customer name",
       sum(payment.amount) as "Total Spent"
from payment
         join customer using (customer_id)
group by customer.first_name, customer.last_name
having sum(payment.amount)>(select "Avg Spent" from avg_spending)
order by "Total Spent" desc ;

-- 5. Rank all customers based on they spent.
select customer.first_name || ' ' || customer.last_name as "customer name",
       sum(payment.amount) as "Total Spent",
       dense_rank() over(order by count(payment.amount) ) as rank
from payment
     join customer using (customer_id)
group by customer.first_name, customer.last_name
order by rank;

-- 6. Total revenue of each month.
select extract(MONTH from payment.payment_date) as month,
       sum(payment.amount) as total_revenue
from payment
group by extract(MONTH from payment.payment_date)
order by month;

-- 7. Top 3 customers in each country who spent most.
with cust_spending as(
    select
        first_name || ' ' || last_name as name,
        country.country,
        dense_rank() over(partition by country.country order by sum(amount) desc) as rank
        from payment
        join customer using (customer_id)
        join address using (address_id)
        join city using (city_id)
        join country using (country_id)
    group by first_name, last_name, country.country
)

select name, country, rank
from cust_spending
where rank<=3
order by country,rank;

-- 8. Actors who appear together more than 5 time.

select actor1.first_name || ' ' || actor1.last_name,
       actor2.first_name || ' ' || actor2.last_name,
       count(fa1.film_id) as movie
from actor as actor1
         join film_actor as fa1
              on actor1.actor_id = fa1.actor_id
         join film_actor as fa2
              on fa1.film_id = fa2.film_id and actor1.actor_id < fa2.actor_id
         join actor as actor2
              on fa2.actor_id = actor2.actor_id
group by actor1.first_name, actor1.last_name, actor2.first_name, actor2.last_name
having count(fa1.film_id)>=5
order by movie desc;

-- 9. Actors who appeared in more than 20 films.
select first_name || ' ' || last_name as name,
       count(film_id) as "Film Count"
from actor
join film_actor using (actor_id)
join film using (film_id)
group by first_name || ' ' || last_name
having count(film_id)>20
order by "Film Count" desc;


-- 10. List the top 10 who have spent the most.
with cust_spending as(
    select
        first_name || ' ' || last_name as name,
        dense_rank() over(order by sum(amount) desc) as rank
    from payment
             join customer using (customer_id)

    group by first_name, last_name
)

select name, rank
from cust_spending
where rank<=10
order by rank;