services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: abc
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/data/db


  app:
    build: .
    container_name: express_web_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongo-data:
  postgres-data:
